version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-west-1:075206908135:task-definition/YTTagTaskDefenition:1"
        LoadBalancerInfo:
          ContainerName: "YoutubeTagContainer"
          ContainerPort: 80
